name: CI/CD on Library App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

jobs:
  npm_config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout of the repo
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm install

  run_be:
    runs-on: ubuntu-latest
    needs: npm_config
    steps:
    - name: Go to server folder
      run: echo cd
    - name: Run server script
      run: node server.js

  run_fe:
    runs-on: ubuntu-latest
    needs: run_be
    steps:
    - name: Run app
      run: npm run start

  ui_tests:
    runs-on: ubuntu-latest
    needs: run_fe
    steps:
    - name: Run UI playwright tests
      run: npm run ui