name: CI/CD on Library App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

jobs:
  npm_config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout of the repo
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm install

  run_be:
    runs-on: ubuntu-latest
    needs: npm_config
    steps:
    - name: Run server script
      run: npm run start-server &

  run_fe:
    runs-on: ubuntu-latest
    needs: run_be
    steps:
    - name: Run app
      run: npm run start &

  ui_tests:
    runs-on: ubuntu-latest
    needs: run_fe
    steps:
    - name: Download playwright
      run: npx playwright install 
    - name: Run UI playwright tests
      run: npm run ui
  
  deploy_render:
    runs-on: ubuntu-latest
    needs: ui_tests
    steps:
    - name: Deploy to producton
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
        api_key: ${{ secrets.MY_RENDER_API_KEY }}